export const Types = {
    LOGIN_INIT: "LOGIN_INIT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_INIT:"LOGOUT_INIT",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE",


    
    COUNT_INCREASE: "COUNT_INCREASE",
    COUNT_DECREASE: "COUNT_DECREASE",
    COUNT_RESET: "COUNT_RESET",
}